services:
  app:
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: "true"
    ports:
      - "3000:3000" # event receiver
      - "3001:3001" # emails sender proxy
    env_file:
      - .env
    environment:
      LOG_LEVEL: info
      NODE_ENV: development
      SALEOR_URL: ${SALEOR_URL:?SALEOR_URL env var is required}
      STATIC_URL: ${STATIC_URL:?STATIC_URL env is required}
      SQS_QUEUE_URL: ${SQS_QUEUE_URL:?SQS_QUEUE_URL env is required}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID?:AWS_ACCESS_KEY_ID env is required}
      AWS_REGION: ${AWS_REGION?:AWS_REGION env is required}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY?:AWS_SECRET_ACCESS_KEY env is required}
      SECRET_MANAGER_APP_CONFIG_PATH: ${SECRET_MANAGER_APP_CONFIG_PATH?:SECRET_MANAGER_APP_CONFIG_PATH env is required}

    volumes:
      - ./src/:/app/src/
