name: Build

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_DEFAULT_REGION: eu-central-1
    steps:
      - uses: actions/checkout@v4

      - name: Create GIT_DESCRIBE variable
        run: |
          echo "GIT_DESCRIBE=$(git describe --broken --tags --always)" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.10.0
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm --version && pnpm install --frozen-lockfile

      - name: Build zip
        run: bash etc/commands/build.sh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::414357773561:role/nimara-mailer
          aws-region: eu-central-1

      - name: Copy ZIP
        run: aws s3 cp artifact.zip s3://marina-artifacts/lambda/lambda-mailer-${{ env.GIT_DESCRIBE }}.zip --quiet

      - name: ZIP tag
        run: echo "${{ env.GIT_DESCRIBE }}"
