name: Code quality

on:
  pull_request:
    branches: ["*"]

jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.10.0
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm --version && pnpm install --frozen-lockfile

      - name: Check prettier
        run: pnpm lint:prettier

      - name: Check eslint
        run: pnpm lint:eslint

      - name: Check types
        run: pnpm lint:tsc

      - name: Check coverage
        run: |
          RESULT="$(pnpm --silent test:coverage:avg)"
          echo "Average coverage: ${RESULT}"
